import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {SlotEngine} from './engines/SlotEngine';
import {games} from './games';
import './style.css';

const sound=(type:'spin'|'win')=>{const C=window.AudioContext||((window as any).webkitAudioContext);if(!C)return;const ctx=new C();const notes=type==='win'?[523,659,784,1046]:[180,220,260];notes.forEach((freq,i)=>{const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=type==='win'?'triangle':'sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.0001,ctx.currentTime+i*.08);gain.gain.exponentialRampToValueAtTime(type==='win'?.12:.06,ctx.currentTime+i*.08+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+i*.08+.16);osc.connect(gain).connect(ctx.destination);osc.start(ctx.currentTime+i*.08);osc.stop(ctx.currentTime+i*.08+.18);});};
function App(){const [selected,setSelected]=useState(0);const [bet,setBet]=useState(100);const [balance,setBalance]=useState(10000);const [result,setResult]=useState<any>(null);const [spinning,setSpinning]=useState(false);const game=games[selected];const spin=()=>{if(spinning||balance<bet)return;sound('spin');setSpinning(true);setResult(null);setTimeout(()=>{const r=new SlotEngine(game).spin(bet,'demo-only');setBalance(b=>b-bet+r.totalPayout);setResult(r);setSpinning(false);if(r.isWin)sound('win')},850)};return <div className="app"><header><b>🎰 SLOT LAB DEMO</b><span>20 máquinas propias • fichas virtuales • no dinero real</span></header><main><aside><h2>Máquinas</h2>{games.map((g,i)=><button className={i===selected?'active':''} onClick={()=>{setSelected(i);setResult(null)}} key={g.id}>{g.title}<small>{g.subtitle}</small></button>)}</aside><section><div className="hero"><div className="sparkles">✦ ✧ ✦</div><p>{game.subtitle}</p><h1>{game.title}</h1><span>Motor común SlotEngine • Demo {selected+1}/20</span></div><div className={`grid ${spinning?'spinning':''} ${result?.isWin?'winner':''}`}>{result?.grid.map((col:any[],c:number)=>col.map((s:any,r:number)=><div className="cell" key={`${c}-${r}`} style={{color:s.color}}>{s.emoji}<small>{s.label}</small></div>)) || [...Array(15)].map((_,i)=><div className="cell" key={i}>❔</div>)}</div><div className="controls"><span>Saldo demo: <b>{balance.toLocaleString('es-AR')}</b></span><label>Apuesta <input type="number" value={bet} min="10" onChange={e=>setBet(Number(e.target.value))}/></label><button className="spin" onClick={spin} disabled={spinning}>{spinning?'GIRANDO…':'GIRAR'}</button></div><div className={`message ${result?.isWin?'win':''}`}>{result?.summary||'Elegí una máquina y girá para probarla.'}</div><p className="note">Animaciones y sonidos generados localmente con CSS y Web Audio API. Demo matemática con fichas virtuales; el RNG requiere validación de servidor para producción.</p></section></main></div>}
createRoot(document.getElementById('root')!).render(<App/>);
